_extends: gh-config

repository:
  description: Enhanced fnmatch with grouping regex and path transformation
  homepage: https://blog.openacid.com
  topics: fnmatch, glob, pattern, path, regex, wildcard
